import {
  IconAlertOctagon,
  IconAlertTriangle,
  IconBan,
  IconFolders,
  IconMailForward,
  IconMailPlus,
  IconTemplate,
  IconMessageCircle,
  IconPhoneCall,
  IconToggleRight,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconMoon,
  IconDotsVertical,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconX,
  IconUsers,
  IconSearch,
  IconActivity,
  IconHistory,
  IconCalendarEvent,
  IconCalendarWeek,
  IconCalendarOff,
  IconPackage,
  IconTruckDelivery,
  IconPackageImport,
  IconBuildingWarehouse,
  IconStairs,
  IconTool,
  IconBuildingCommunity,
  IconClipboardCheck,
  IconInbox,
  IconCertificate,
  IconHeartbeat,
  IconForms
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  spinner: IconLoader2,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  check: IconCheck,
  // Operational navigation
  teamTasks: IconUsers,
  search: IconSearch,
  history: IconHistory,
  activity: IconActivity,
  booking: IconCalendarEvent,
  planner: IconCalendarWeek,
  availability: IconCalendarOff,
  materials: IconPackage,
  orders: IconTruckDelivery,
  goodsIn: IconPackageImport,
  stock: IconBuildingWarehouse,
  scaffold: IconStairs,
  install: IconTool,
  commissioning: IconClipboardCheck,
  programmes: IconBuildingCommunity,
  intake: IconInbox,
  skills: IconCertificate,
  system: IconHeartbeat,
  forms: IconForms,
  calls: IconPhoneCall,
  issues: IconAlertOctagon,
  cancellations: IconBan,
  files: IconFolders,
  communications: IconMailForward,
  composeEmail: IconMailPlus,
  emailTemplates: IconTemplate,
  chat: IconMessageCircle,
  release: IconToggleRight
};
