import 'server-only';

import { createDataClient } from '@/lib/supabase/data';
import type { SupabaseClient } from '@supabase/supabase-js';

/**
 * A typed client for the programme tables.
 *
 * TODO(remove this file): it exists ONLY because `npm run db:types` cannot run in
 * this environment. Once that works, regenerate `src/types/database.ts`, delete
 * this file, and change `programmeDb()` back to `createDataClient()` at its 16
 * call sites in ./queries.ts. Nothing else depends on it. The fault is in the
 * generator's connection, not in this project's schema: the Supabase CLI's type
 * generator connects to the database on its own container's default port (5432)
 * and fails password authentication against this project's custom ports (5532x).
 * That is a tooling fix, deliberately not attempted here.
 *
 * `src/types/database.ts` is generated by `npm run db:types`, which cannot run
 * in this environment (the generator connects to the database on its default
 * port inside its own container and fails authentication against this project's
 * custom ports). Rather than hand-edit a generated file - which the next
 * successful generation would silently throw away - the programme relations are
 * declared here, in the same shape the generator produces, and applied as the
 * client's schema.
 *
 * This is a narrowing, not a widening: programme queries are checked against
 * these declarations instead of being cast to `any`. When `db:types` works
 * again, delete this file and use `createDataClient()` directly.
 *
 * The declarations describe what the database has; the database remains the
 * authority on every rule about it. Writes are absent on purpose: there is no
 * client write path to a programme table - every change is a command.
 */

type Timestamp = string;
type Uuid = string;
type Json = unknown;

type ProgrammeRow = {
  id: Uuid;
  code: string;
  name: string;
  client_name: string | null;
  status: string;
  starts_on: string | null;
  ends_on: string | null;
  visit_form_id: Uuid | null;
  field_map: Json;
  outcome_map: Json;
  signal_config: Json;
  property_visibility: string;
  synthetic: boolean;
  notes: string | null;
  created_at: Timestamp;
  created_by: Uuid | null;
  updated_at: Timestamp;
  updated_by: Uuid | null;
  version: number;
};

type ProgrammePropertyRow = {
  id: Uuid;
  programme_id: Uuid;
  external_ref: string;
  address_line1: string;
  address_line2: string | null;
  town: string | null;
  postcode: string | null;
  postcode_norm: string | null;
  expected_meter_serial: string | null;
  expected_serial_norm: string | null;
  existing_sim_serial: string | null;
  notes: string | null;
  source_row: Json;
  import_id: Uuid | null;
  active: boolean;
  synthetic: boolean;
  created_at: Timestamp;
  created_by: Uuid | null;
  updated_at: Timestamp;
  updated_by: Uuid | null;
  version: number;
};

type ProgrammeAssignmentRow = {
  id: Uuid;
  programme_id: Uuid;
  property_id: Uuid | null;
  person_id: Uuid;
  active: boolean;
  assigned_on: string;
  ended_on: string | null;
  note: string | null;
  created_at: Timestamp;
  created_by: Uuid | null;
  updated_at: Timestamp;
  updated_by: Uuid | null;
  version: number;
};

type ProgrammeVisitRow = {
  id: Uuid;
  programme_id: Uuid;
  property_id: Uuid;
  installer_id: Uuid;
  form_id: Uuid | null;
  form_revision_id: Uuid | null;
  submission_id: Uuid | null;
  outcome: string | null;
  actual_meter_serial: string | null;
  actual_serial_norm: string | null;
  /** numeric(14,3): PostgREST sends it as a string. */
  meter_reading: string | null;
  new_sim_serial: string | null;
  csq: number | null;
  installer_comments: string | null;
  meter_serial_matches: boolean | null;
  signal_classification: string | null;
  portal_check_required: boolean;
  review_required: boolean;
  review_reasons: string[];
  recommended_disposition: string | null;
  review_status: string;
  disposition: string;
  portal_verification: string | null;
  action_note: string | null;
  reviewed_by: Uuid | null;
  reviewed_at: Timestamp | null;
  visit_date: string | null;
  submitted_at: Timestamp | null;
  synthetic: boolean;
  created_at: Timestamp;
  created_by: Uuid | null;
  updated_at: Timestamp;
  updated_by: Uuid | null;
  version: number;
};

type ProgrammeImportRow = {
  id: Uuid;
  programme_id: Uuid;
  filename: string;
  header: string[];
  row_count: number;
  mapping: Record<string, number> | null;
  status: string;
  valid_rows: number | null;
  invalid_rows: number | null;
  created_count: number | null;
  updated_count: number | null;
  applied_at: Timestamp | null;
  applied_by: Uuid | null;
  created_at: Timestamp;
  created_by: Uuid | null;
  updated_at: Timestamp;
  updated_by: Uuid | null;
  version: number;
};

type ProgrammeImportRowRow = {
  id: Uuid;
  import_id: Uuid;
  row_index: number;
  cells: string[];
  mapped: Record<string, string | null> | null;
  problems: { field: string; problem: string }[];
  action: string | null;
  property_id: Uuid | null;
};

/** Only the evidence columns the programme screens read. */
type EvidenceRow = {
  id: Uuid;
  programme_visit_id: Uuid | null;
  scope: string;
  category: string;
  filename: string;
  original_filename: string | null;
  mime_type: string | null;
  size_bytes: number | null;
  upload_status: string;
  trashed_at: Timestamp | null;
  uploaded_by: Uuid | null;
  created_at: Timestamp;
};

type PersonRow = {
  id: Uuid;
  display_name: string | null;
  email: string | null;
  active: boolean;
};

/**
 * The generated shape. Insert/Update are declared because the client type
 * requires them, NOT because a client may write: RLS grants SELECT only and
 * every change is a command, which is what actually forbids it.
 */
type Relation<T> = {
  Row: T;
  Insert: Partial<T>;
  Update: Partial<T>;
  Relationships: [];
};

export type ProgrammeDatabase = {
  public: {
    Tables: {
      programmes: Relation<ProgrammeRow>;
      programme_properties: Relation<ProgrammePropertyRow>;
      programme_assignments: Relation<ProgrammeAssignmentRow>;
      programme_visits: Relation<ProgrammeVisitRow>;
      programme_imports: Relation<ProgrammeImportRow>;
      programme_import_rows: Relation<ProgrammeImportRowRow>;
      evidence: Relation<EvidenceRow>;
      people: Relation<PersonRow>;
    };
    Views: { [_ in never]: never };
    Functions: {
      programmes_enabled: {
        Args: { [_ in never]: never };
        Returns: boolean;
      };
      programme_visit_form: {
        Args: { p_programme_id: Uuid };
        Returns: Record<string, unknown> | null;
      };
      programme_signal_class: {
        Args: { p_programme_id: Uuid; p_value: number | null };
        Returns: string | null;
      };
      execute_operations_read: {
        Args: { p_request: Json };
        Returns: Record<string, unknown> | null;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

export type ProgrammeClient = SupabaseClient<ProgrammeDatabase, 'public'>;

/**
 * The signed-in person's client, typed for the programme relations. RLS decides
 * what it returns; in developer preview it is the preview client, which cannot
 * write at all.
 */
export async function programmeDb(): Promise<ProgrammeClient> {
  return (await createDataClient()) as unknown as ProgrammeClient;
}
